// Sidebar is generated from ../docs; ordering comes from each page's
// `sidebar_position` frontmatter.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
