#!/usr/bin/env python3
"""Fit every slide inside the 720px print page box, and prove it.

Why this exists
---------------
The deck is exported to PDF by headless Chrome (submission/README-export.md).
An over-tall slide does not report an error - it degrades, and which way it
degrades depends on one CSS declaration:

  * overflow:hidden  -> the excess is silently DESTROYED. The PDF looks fine at
    a glance and is missing whole paragraphs. This shipped: eight of fifteen
    pages in the committed slides.pdf were losing content, including most of
    the "Results" slide.
  * overflow:visible -> the excess spills onto the next page and paints ON TOP
    of the following slide. Detectable by eye, but still wrong.

Neither is caught by looking at the deck in a browser, because on screen the
page box is the viewport and in print it is the 1280x720 @page. Any `vh` unit
therefore resolves to two different numbers, and a screen-based measurement -
which is what this repo used to recommend - is structurally unable to see the
print geometry. It reported "0 overflowing" for every one of those eight pages.

So this script measures the slides in PRINT geometry: it applies the @media
print rules on screen in a 1280x720 window, where `vh` resolves to exactly the
value it will have on the printed page. Nothing here is a proxy for the export;
it is the same geometry the export uses.

What it does
------------
Slides that do not fit get a per-slide font scale in a generated block of CSS,
so the content is preserved rather than trimmed - shrinking type is a
reversible, visible tradeoff, whereas deleting a judge-facing sentence is not.
Because the padding is fixed px and only the type scales, the relationship
between scale and height is not linear, so it iterates to a fixed point.

    python scripts/fit_slides.py           # measure, fit, write the block
    python scripts/fit_slides.py --check   # measure only; exit 1 if any slide
                                           # overflows or the block is stale

--check needs Chrome, so it is a pre-export gate rather than a CI test (CI has
no browser). Run it before re-exporting the PDF.
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DECK = ROOT / "submission/video/slides.html"
CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

PAGE_H = 720
START, END = "<!-- fit:auto -->", "<!-- /fit:auto -->"
# Below this the type is too small to read from the back of a room; the script
# reports it and stops rather than quietly shipping an unreadable slide, because
# a slide that needs this much shrink needs an editorial cut instead.
MIN_SCALE = 0.72
# Matches `section img { max-height }` in the deck's own print rules.
IMG_MAX = 300


def strip_block(text: str) -> str:
    if START not in text:
        return text
    head, rest = text.split(START, 1)
    return head + rest.split(END, 1)[1]


def build_block(scales: dict[int, float]) -> str:
    if not scales:
        rules = "  /* every slide fits unscaled */\n"
    else:
        # The screenshot slides are dominated by a fixed-height image, so scaling
        # only the type asymptotes above 720px and never converges. Scale the
        # image on the same slide by the same factor.
        rules = "".join(
            f"    section:nth-of-type({n}) {{ font-size:{s:.3f}em; }}\n"
            f"    section:nth-of-type({n}) img {{ max-height:{IMG_MAX * s:.0f}px; }}\n"
            for n, s in sorted(scales.items())
        )
    return (
        f"{START}\n<!-- generated by scripts/fit_slides.py - do not hand-edit -->\n"
        f"<style>\n  @media print {{\n{rules}  }}\n</style>\n{END}"
    )


def measure(text: str) -> list[int]:
    """Height of every section under the print rules, in the print page box."""
    # Apply @media print on screen. The window is sized to the @page box so vh
    # resolves identically to the export - this is the whole point of the file.
    # ALL occurrences, not just the first: the generated fit block is itself an
    # @media print rule, and leaving it as print while promoting the deck's own
    # block to screen measures the layout with the scales silently inert - which
    # looks exactly like "the fit had no effect" and never converges.
    harness = text.replace("@media print {", "@media screen {")
    harness += """
<script>
window.addEventListener('load', () => setTimeout(() => {
  document.title = 'M' + JSON.stringify(
    [...document.querySelectorAll('section')].map(s => s.scrollHeight));
}, 1200));
</script>"""
    # The harness MUST live beside the deck. slides.html loads screenshots with
    # relative paths (../images/*.png); measured from a temp directory those
    # resolve to nothing, the images collapse to their alt text, and the slides
    # carrying them measure ~300px short - reporting "fits" for slides that then
    # spill onto the next page in the real export. That is how slides 13 and 14
    # passed a green measurement and still lost their last paragraph.
    page = DECK.parent / ".fit-measure.html"
    try:
        page.write_text(harness)
        dom = subprocess.run(
            [CHROME, "--headless=new", "--disable-gpu", f"--window-size=1280,{PAGE_H}",
             "--virtual-time-budget=9000", "--dump-dom", f"file://{page}"],
            capture_output=True, text=True, timeout=180, check=False,
        ).stdout
    finally:
        page.unlink(missing_ok=True)
    m = re.search(r"<title>M(\[[^<]*\])</title>", dom)
    if not m:
        raise SystemExit("measurement harness produced no result (Chrome failed?)")
    return json.loads(m.group(1))


def titles(text: str) -> list[str]:
    return [
        re.sub(r"\s+", " ", re.sub("<[^>]*>", "", h)).strip()[:44]
        for h in re.findall(r"<h[12][^>]*>(.*?)</h[12]>", text, re.DOTALL)
    ]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="measure only; do not write")
    args = ap.parse_args()

    original = DECK.read_text()
    names = titles(original)

    if args.check:
        heights = measure(original)
        over = [(i + 1, h) for i, h in enumerate(heights) if h > PAGE_H]
        for i, h in enumerate(heights):
            flag = f"+{h - PAGE_H} OVER" if h > PAGE_H else "fits"
            print(f"  {i + 1:2}  {h:5}px  {flag:>10}   {names[i] if i < len(names) else ''}")
        if over:
            print(f"\n{len(over)} slide(s) overflow the {PAGE_H}px page box; "
                  f"the PDF will lose or overlap content.\nrun: python scripts/fit_slides.py",
                  file=sys.stderr)
            return 1
        print(f"\n  all {len(heights)} slides fit the {PAGE_H}px page box")
        return 0

    base = strip_block(original)
    scales: dict[int, float] = {}
    for round_ in range(1, 7):
        text = base.replace("</head>", build_block(scales) + "\n</head>", 1) \
            if "</head>" in base else build_block(scales) + base
        heights = measure(text)
        over = {i + 1: h for i, h in enumerate(heights) if h > PAGE_H}
        print(f"  pass {round_}: {len(over)} of {len(heights)} slides over {PAGE_H}px")
        if not over:
            break
        for n, h in over.items():
            cur = scales.get(n, 1.0)
            # Only the type scales; the fixed px padding does not. Solve on the
            # content height alone, then damp slightly so we approach from below.
            pad = 86
            want = (PAGE_H - pad) / max(h - pad, 1)
            scales[n] = round(max(cur * want * 0.985, MIN_SCALE), 3)
    else:
        print("did not converge after 6 passes", file=sys.stderr)
        return 1

    DECK.write_text(text)
    if scales:
        print(f"\n  scaled {len(scales)} slide(s) to fit:")
        for n, s in sorted(scales.items()):
            note = "  <- at the floor; consider an editorial cut" if s <= MIN_SCALE else ""
            print(f"    slide {n:2} {int(s * 100):3}%  {names[n - 1] if n <= len(names) else ''}{note}")
    print(f"\n  wrote {DECK.relative_to(ROOT)}; now re-export the PDF")
    return 0


if __name__ == "__main__":
    sys.exit(main())
